services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: quote-of-day
    ports:
      - "3001:3001"
      - "9229:9229"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quote_of_day
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network
  flyway:
    image: flyway/flyway
    container_name: flyway-migrations
    depends_on:
      - postgres
    volumes:
      - ./backend/migrations:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/quote_of_day
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=password
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
    command: [ "migrate" ]
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
